# Use root/example as user/password credentials
version: '3.1'

services:
  db:
    image: mysql:8.0.29-debian
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: 1234
      TZ: Europe/Helsinki
    volumes:
      # Mount folder with DB initialization scripts (they run when container starts)
      - ./docker/mysql:/docker-entrypoint-initdb.d
      # - ./db-data:/var/lib/mysql # Mount data in host (no need)

  adminer:
    image: adminer
    restart: always
    ports:
      - 8080:8080