# Use root/example as user/password credentials
version: '3.1'

services:
  db:
    image: mysql:debian
    # build:
    #   context: ./
    #   dockerfile: Dockerfile
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: 1234
      TZ: Europe/Helsinki
    volumes:
      # Mount folder with DB initialization scripts (they run when container starts)
      - ./db_setup.sql:/docker-entrypoint-initdb.d/db_setup.sql
      # - ./db-data:/var/lib/mysql # Mount data in host (no need)

  adminer:
    image: adminer
    restart: always
    ports:
      - 8080:8080